Update to be C++11 compliant
C++11 is stricter about running literals together:

    error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
    n_buf = sprintf(op->numbufs, "%"PRId64, num_i);